[Site 294] Adjust text styles and spacings on article page
labcodes/blog pull request #119
Opened 2020-10-20 23:27 UTC by nenispng

**Link to issue:**
https://labcodes.atlassian.net/browse/SITE-294

**Description:**
Added new spacing and radii variables constructed on 4px baseline multiplication
General variables file organization
New spacing variables applied to article page text styles and its media queries
Font style and spacing adjusted to match figma design file

2020-10-27 17:43 UTC, fernandolins requested changes

2020-10-27 17:43 UTC, fernandolins commented on themes/medius/scss/article.scss
> +    font-size: 24px;
Should it be a variable?

2020-10-27 17:43 UTC, fernandolins commented on themes/medius/scss/article.scss
> +    font-size: 18px;
Should it be a variable?

2020-10-27 17:43 UTC, fernandolins commented on themes/medius/scss/article.scss
> +      font-size: 24px;
Should it be a variable?

2020-10-27 17:43 UTC, fernandolins commented on themes/medius/scss/article.scss
> +      font-size: 22px;
Should it be a variable?

2020-10-27 17:43 UTC, fernandolins commented on themes/medius/scss/article.scss
> +      margin: 0 0 $spacing-6 0;
Should it be implement at Line 90?

2020-10-27 17:43 UTC, fernandolins commented on themes/medius/scss/article.scss
> +      line-height: $spacing-7;
It was already defined on Lines 137 and 138.

2020-10-27 17:43 UTC, fernandolins commented on themes/medius/scss/article.scss
> +      font-weight: $weight-bold;
It was already defined on Line 131.

2020-10-27 17:43 UTC, fernandolins commented on themes/medius/scss/article.scss
> +      font-weight: $weight-medium;
It was already defined on Line 125.

2020-10-27 17:43 UTC, fernandolins commented on themes/medius/scss/article.scss
> +      color: $black-87;
It was already defined on block Lines 117 to 120.

2020-10-27 17:43 UTC, fernandolins commented on themes/medius/scss/article.scss
> +      line-height: 48px;
I'm wondering if `line-height` should be defined as literal value or using spaces variables.
What do you think about it?

2020-10-28 15:32 UTC, nenispng commented on themes/medius/scss/article.scss
> +    font-size: 24px;
this value is used only on the article page

2020-10-28 15:32 UTC, nenispng commented on themes/medius/scss/article.scss
> +    font-size: 18px;
this value is used only on the article page

2020-10-28 15:32 UTC, nenispng commented on themes/medius/scss/article.scss
> +      font-size: 24px;
this value is used only on the article page

2020-10-28 15:32 UTC, nenispng commented on themes/medius/scss/article.scss
> +      font-size: 22px;
this value is used only on the article page

2020-10-28 15:36 UTC, nenispng commented on themes/medius/scss/article.scss
> +      margin: 0 0 $spacing-6 0;
No, those are the values for tablet-up. Margin removed

2020-10-28 15:39 UTC, nenispng commented on themes/medius/scss/article.scss
> +      font-weight: $weight-bold;
Fixed font-weight. Sized is not repeated.

2020-10-28 15:40 UTC, nenispng commented on themes/medius/scss/article.scss
> +      font-weight: $weight-medium;
Fixed font-weight. Sized is not repeated.

2020-10-28 15:41 UTC, nenispng commented on themes/medius/scss/article.scss
> +      color: $black-87;
Fixed

2020-10-28 15:47 UTC, nenispng commented on themes/medius/scss/article.scss
> +      line-height: 48px;
This specific line height value only occurs for the post title inside the article page. I am going to change that into an operation so it makes more sense to anyone looking at it. 

Using `(12 * $baseline)` makes more sense to me because the baseline pixels (4px) are used to calculate the line heights while designing at figma, so, it might not become a variable, since the value 48px it is not used anywhere else, it indicates that it is an operation that used the baseline grid as source)

2020-10-28 18:09 UTC, fernandolins approved these changes

2020-10-28 18:09 UTC, merged