[Site 295] Fix ordered and unordered lists
labcodes/blog pull request #120
Opened 2020-10-21 20:39 UTC by nenispng

**Link to issue:**
https://labcodes.atlassian.net/browse/SITE-295

**Description:**
Now we have OL and UL styles capable of up to 3 levels nesting
The markers were created using ::before and native Freight Sans font capabilities
Mixins were created so the markers were properly placed and list's width also fit the mother container
New variables to handle lists easily

_Sorry about the reverted commits._

2020-10-27 18:07 UTC, fernandolins requested changes

2020-10-27 18:07 UTC, fernandolins commented on themes/medius/scss/article.scss
> +    font-feature-settings: $linear-number;
It is already `inherit` from `.article-content`

2020-10-27 18:07 UTC, fernandolins commented on themes/medius/scss/mixins.scss
> +  position: relative;
All li have already this settings.

2020-10-27 18:07 UTC, fernandolins commented on themes/medius/scss/mixins.scss
> +  position: relative;
All li have already this settings.

2020-10-27 18:07 UTC, fernandolins commented on themes/medius/scss/article.scss
> +      @include fix-list-width($ul-lvl-1);
I didn't get it why did you put it here? 
if you have already defined a `ul > li` above

2020-10-27 18:07 UTC, fernandolins commented on themes/medius/scss/article.scss
> +        @include list-item-width($ul-lvl-1);
Same thing here

2020-10-28 16:21 UTC, nenispng commented on themes/medius/scss/article.scss
> +    font-feature-settings: $linear-number;
Fixed

2020-10-28 16:30 UTC, nenispng commented on themes/medius/scss/mixins.scss
> +  position: relative;
Fixed

2020-10-28 16:30 UTC, nenispng commented on themes/medius/scss/mixins.scss
> +  position: relative;
Fixed

2020-10-28 16:38 UTC, nenispng commented on themes/medius/scss/article.scss
> +      @include fix-list-width($ul-lvl-1);
Above it is defined the common settings to OL and UL.
This part is UL specific to fix the LIs widths and make them fit within the container.

2020-10-28 16:38 UTC, nenispng commented on themes/medius/scss/article.scss
> +        @include list-item-width($ul-lvl-1);
Above it is defined the common settings to OL and UL.
This part is UL specific to fix the marker's width settings to make the line break outside the marker area

2020-10-28 19:40 UTC, fernandolins approved these changes

2020-10-28 19:41 UTC, merged