[Site-311] Adjust post card
labcodes/blog pull request #124
Opened 2020-10-28 22:39 UTC by nenispng

**Link to issue 🔗**
https://labcodes.atlassian.net/browse/SITE-311

**What's new? ✨**
Various adjustments on the post card including:
- New fonts for title
- New separator with native font ornament font-feature
- Post cover position fixed (now properly centered)
- No more author avatar image
- Category tags are now spans instead of figcaptions
- Jello effect is more subtle now
- New hover effects 
- Color variables updated
- Post descriptions are now disabled by default

2020-11-03 13:36 UTC, fernandolins requested changes

2020-11-03 13:36 UTC, fernandolins commented on themes/medius/scss/variables.scss
> +$development-bg: $purple;
```suggestion
$business: $dark-mustard;
$conferences: $dark-turquoise;
$design: $dark-coral;
$development: $dark-purple;

$business-bg: $mustard-40;
$conferences-bg: $turquoise;
$design-bg: $coral-40;
$development-bg: $purple-60;
```

You should use the right name here

2020-11-03 13:36 UTC, fernandolins commented on themes/medius/scss/home.scss
> +  // }
Will it be useful?
otherwise, could you remove it?

2020-11-03 13:36 UTC, fernandolins commented on themes/medius/scss/home.scss
> +    // }
Will it be useful?
otherwise, could you remove it?

2020-11-04 13:12 UTC, nenispng commented on themes/medius/scss/home.scss
> +  // }
This code was used later on https://github.com/labcodes/blog/tree/site-292

2020-11-04 13:12 UTC, nenispng commented on themes/medius/scss/home.scss
> +    // }
This code was used later on https://github.com/labcodes/blog/tree/site-292

2020-11-04 21:19 UTC, merged