[Site-310] Adjust highlight post card
labcodes/blog pull request #125
Opened 2020-10-28 22:57 UTC by nenispng

This branch name does not match the task name. Sorry :(

**Link to issue 🔗**
https://labcodes.atlassian.net/browse/SITE-310

**What's new? ✨**
- Deleted some deprecated color variables
- Fixed image and content position and size on highlight card
- Brand-new highlight post card on mobile viewports
- Hover and focus effects for all post cards
- Fixed display issue on wrapper div
- General file organization to make some components work anywhere

2020-11-03 13:57 UTC, fernandolins requested changes

2020-11-03 13:57 UTC, fernandolins commented on themes/medius/scss/home.scss
> +    background-color: $mustard;
```suggestion
    background-color: $mustard-40;
```

2020-11-03 13:57 UTC, fernandolins commented on themes/medius/scss/home.scss
> +    background-color: $teal;
```suggestion
    background-color: $teal-40;
```

2020-11-03 13:57 UTC, fernandolins commented on themes/medius/scss/home.scss
> +    background-color: $coral;
```suggestion
    background-color: $coral-40;
```

2020-11-03 13:57 UTC, fernandolins commented on themes/medius/scss/home.scss
> +    background-color: $purple;
```suggestion
    background-color: $purple-60;
```

2020-11-04 13:09 UTC, nenispng commented on themes/medius/scss/home.scss
> +    background-color: $mustard;
There are variables to inserting the default shade for each color stack. Are you proposing we dont use those variables?

2020-11-04 13:09 UTC, nenispng commented on themes/medius/scss/home.scss
> +    background-color: $teal;
There are variables to inserting the default shade for each color stack. Are you proposing we dont use those variables?

2020-11-04 13:09 UTC, nenispng commented on themes/medius/scss/home.scss
> +    background-color: $coral;
There are variables to inserting the default shade for each color stack. Are you proposing we dont use those variables?

2020-11-04 13:10 UTC, nenispng commented on themes/medius/scss/home.scss
> +    background-color: $purple;
There are variables to inserting the default shade for each color stack. Are you proposing we dont use those variables?

2020-11-04 21:40 UTC, fernandolins requested changes

2020-11-04 21:40 UTC, fernandolins commented on themes/medius/scss/home.scss
> +    background-color: $mustard;
Yes, if we have created the new variables to be replaced the old ones.
Why shouldn't we use the new ones?

2020-11-06 18:08 UTC, nenispng commented on themes/medius/scss/home.scss
> +    background-color: $mustard;
This is a new one. At least it is how it is been used on the DS. We have the number code for each stack position and a general variable, like the one above, $mustard, to load the default value to the mustard color stack

2020-11-06 18:31 UTC, merged