[Site-314]
labcodes/blog pull request #128
Opened 2020-10-30 20:56 UTC by nenispng

**Link to issue 🔗** 
https://labcodes.atlassian.net/browse/SITE-314

**What's new? ✨** 
- New treatment for images with rounded corners
- Images are now centered and display their original size. If too big for the container, they will fit inside.
- Blockquote simple adjustments. Still doesn't match the redesign, but looks better

**Extra 🌟** 
- New separator style

2020-11-03 14:45 UTC, fernandolins requested changes

2020-11-03 14:45 UTC, fernandolins commented on themes/medius/scss/article.scss
> +    color:$mineral-30;
Why do you need this line?

2020-11-03 14:45 UTC, fernandolins commented on themes/medius/scss/article.scss
> +    figcaption {
I couldn't test it.
Where can I find a post with a figcaption img?

2020-11-03 14:45 UTC, fernandolins commented on themes/medius/scss/article.scss
> +    border-radius: $baseline;
This way you implemented the left border without rounded edges as we have on Figma UI Design.
What do you think to do it using `:before`?

2020-11-04 12:30 UTC, nenispng commented on themes/medius/scss/article.scss
> +    color:$mineral-30;
this is the separator line

2020-11-04 12:31 UTC, nenispng commented on themes/medius/scss/article.scss
> +    figcaption {
we currently dont have any, but we should. the correct way to insert image capitions is using <figcaption>

2020-11-04 12:32 UTC, nenispng commented on themes/medius/scss/article.scss
> +    border-radius: $baseline;
I tried but I didnt acheive any good results. We can pair later so you can help me.

2020-11-04 21:42 UTC, fernandolins commented on themes/medius/scss/article.scss
> +    color:$mineral-30;
I know.
but you can remove the line 67.
add color is not necessary.

2020-11-04 21:42 UTC, fernandolins commented on themes/medius/scss/article.scss
> +    border-radius: $baseline;
Sure, we can do it later.

2020-11-04 21:43 UTC, fernandolins commented on themes/medius/scss/article.scss
> +    figcaption {
ok, but how can I test it?

2020-11-05 12:36 UTC, nenispng commented on themes/medius/scss/article.scss
> +    figcaption {
we can't, yet. we need to inform people to use a figcaption in their next posts.

2020-11-05 12:37 UTC, nenispng commented on themes/medius/scss/article.scss
> +    color:$mineral-30;
why not? this is the color I want to apply.

2020-11-05 12:48 UTC, nenispng commented on themes/medius/scss/article.scss
> +    color:$mineral-30;
sorry. now I see the mistake :neckbeard:

2020-11-05 14:55 UTC, fernandolins commented on themes/medius/scss/article.scss
> +    figcaption {
ok. But I want to test it.
how can I use figcaption locally?

2020-11-05 17:51 UTC, nenispng commented on themes/medius/scss/article.scss
> +    figcaption {
@fernandolins I have chosen to remove the <figcaption> style so we can make it simpler and move on with this PR.

2020-11-05 18:30 UTC, fernandolins requested changes

2020-11-05 18:30 UTC, fernandolins commented on themes/medius/scss/article.scss
> +      padding: $baseline 0 $baseline $spacing-5;
```suggestion
      padding: $baseline 0 $baseline $spacing-6;
```

2020-11-05 18:30 UTC, fernandolins commented on themes/medius/scss/article.scss
> +  }
```suggestion
  blockquote {
    &:before {
      content: "";
      position: absolute;
      left: 0;
      top: 0;
      height: 100%;
      border: 2px solid $mineral-70;
      border-radius: $baseline;
    }

    font-style: inherit;
    margin: 0 0 $spacing-6 0;
    padding: 0 0 0 $spacing-5;
    border: none;
    position: relative;
  }
```

2020-11-05 18:52 UTC, fernandolins approved these changes
LGTM

2020-11-05 18:52 UTC, merged