[Site-313] Adjust the appendix present on every article page bottom
labcodes/blog pull request #129
Opened 2020-11-04 20:38 UTC by nenispng

**Link to issue 🔗** 
https://labcodes.atlassian.net/browse/SITE-313

What's new? ✨ 
- text, link and tag adjustments on newsletter invite
- margin, color and width adjustments on CTA
- width adjustment on disqus widget

2020-11-04 21:52 UTC, fernandolins requested changes

2020-11-04 21:52 UTC, fernandolins commented on themes/medius/templates/includes/call-to-action.html
> +      We're thrilled to hear about your project. </br>
Why did you add a slash to br html tag?
https://www.w3schools.com/tags/tag_br.asp

2020-11-04 21:52 UTC, fernandolins commented on themes/medius/templates/includes/article-footer.html
> +</br>
Why did you add a slash to br html tag?
https://www.w3schools.com/tags/tag_br.asp

2020-11-04 21:52 UTC, fernandolins commented on themes/medius/templates/includes/article-footer-pt.html
> +</br>
Why did you add a slash to br html tag?
https://www.w3schools.com/tags/tag_br.asp

2020-11-04 21:52 UTC, fernandolins commented on themes/medius/scss/shared.scss
> +      background-color: $purple;
```suggestion
      background-color: $purple-60;
```

2020-11-05 18:25 UTC, nenispng commented on themes/medius/templates/includes/call-to-action.html
> +      We're thrilled to hear about your project. </br>
I have mistaken html with xhtml. Already commited the fixes.

2020-11-05 18:25 UTC, nenispng commented on themes/medius/templates/includes/article-footer.html
> +</br>
I have mistaken html with xhtml. Already commited the fixes.

2020-11-05 18:25 UTC, nenispng commented on themes/medius/templates/includes/article-footer-pt.html
> +</br>
I have mistaken html with xhtml. Already commited the fixes.

2020-11-06 18:21 UTC, fernandolins approved these changes
LGTM

2020-11-06 18:27 UTC, merged