Technical Debt: Why it'll ruin your software
labcodes/blog pull request #99
Opened 2020-09-25 17:01 UTC by luanfonceca

TODO
- [x] Add cover image
- [ ] Add thumbnail

Portuguese article:
- [x] Move copy from paper to blogpost
- [x] Download images
- [ ] Change header images to text titles

English article:
- [ ] Move copy from paper to blogpost
- [ ] Download images
- [ ] Change header images to text titles

2020-10-06 17:52 UTC, fernandolins requested changes

2020-10-06 17:52 UTC, fernandolins commented on content/articles/pt/tech-debt.md
> +![Foto da Torre de Pisa](../../images/tech-debt/pisa-tower.png)
```suggestion
![Foto da Torre de Pisa]({static}/images/tech-debt/pisa-tower.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/pt/tech-debt.md
> +![Foto de Chico trabalhando](../../images/tech-debt/chico-the-purrgrammer.png)
```suggestion
![Foto de Chico trabalhando]({static}/images/tech-debt/chico-the-purrgrammer.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/pt/tech-debt.md
> +Category: Development, Technical Debt
```suggestion
Category: Development, All posts
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/pt/tech-debt.md
> +![Chico brincando](../../images/tech-debt/chico-features.png)
```suggestion
![Chico brincando]({static}/images/tech-debt/chico-features.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/pt/tech-debt.md
> +![Chico positivo porque entregou o projeto a tempo](../../images/tech-debt/chico-delivered.png)
```suggestion
![Chico positivo porque entregou o projeto a tempo]{static}/images/tech-debt/chico-delivered.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/pt/tech-debt.md
> +![Vários gatinhos revisando o código de Chico](../../images/tech-debt/chico-team-review.png)
```suggestion
![Vários gatinhos revisando o código de Chico]({static}/images/tech-debt/chico-team-review.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/pt/tech-debt.md
> +![Chico apreensivo, pois seu código tinha bugs](../../images/tech-debt/chico-bugs.png)
```suggestion
![Chico apreensivo, pois seu código tinha bugs]({static}/images/tech-debt/chico-bugs.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/pt/tech-debt.md
> +![Chico positivo pois sabia que no futuro ele vai corrigir tudo](../../images/tech-debt/chico-refactoring.png)
```suggestion
![Chico positivo pois sabia que no futuro ele vai corrigir tudo]({static}/images/tech-debt/chico-refactoring.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/pt/tech-debt.md
> +![Torre de Pisa ao fundo com turistas tirando foto tentando segura-lá](../../images/tech-debt/pisa-tower-is-sustainable.png)
```suggestion
![Torre de Pisa ao fundo com turistas tirando foto tentando segura-lá]({static}/images/tech-debt/pisa-tower-is-sustainable.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/pt/tech-debt.md
> +![Custo de baixa qualidade de software: 2.84 trihões de dólares](../../images/tech-debt/bad-quality-software-costs.png)
```suggestion
![Custo de baixa qualidade de software: 2.84 trihões de dólares]({static}/images/tech-debt/bad-quality-software-costs.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/pt/tech-debt.md
> +![Vários gatinhos em uma Reuniões de Revisão](../../images/tech-debt/tech-debt-review.png)
```suggestion
![Vários gatinhos em uma Reuniões de Revisão]({static}/images/tech-debt/tech-debt-review.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/pt/tech-debt.md
> +![Princípio de pareto](../../images/tech-debt/pareto-principle.png)
```suggestion
![Princípio de pareto]({static}/images/tech-debt/pareto-principle.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/pt/tech-debt.md
> +![I.M.P.A.C.T](../../images/tech-debt/impact.png)
```suggestion
![I.M.P.A.C.T]({static}/images/tech-debt/impact.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/pt/tech-debt.md
> +![Chico triste pois suas má-decisões afetam o projeto](../../images/tech-debt/our-responsability-en.png)
```suggestion
![Chico triste pois suas má-decisões afetam o projeto]({static}/images/tech-debt/our-responsability-en.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/pt/tech-debt.md
> +![Quadrante de Débito Técnico de Martin Fowler](../../images/tech-debt/tech-debt-quadrant.png)
```suggestion
![Quadrante de Débito Técnico de Martin Fowler]({static}/images/tech-debt/tech-debt-quadrant.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/en/tech-debt.md
> +Category: Development, Technical Debt
```suggestion
Category: Development, All posts
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/en/tech-debt.md
> +![Pisa Tower picture](../../images/tech-debt/pisa-tower.png)
```suggestion
![Pisa Tower picture]({static}/images/tech-debt/pisa-tower.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/en/tech-debt.md
> +![John working in a computer](../../images/tech-debt/chico-the-purrgrammer.png)
```suggestion
![John working in a computer]({static}/images/tech-debt/chico-the-purrgrammer.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/en/tech-debt.md
> +![John playing with a ball](../../images/tech-debt/chico-features.png)
```suggestion
![John playing with a ball]({static}/images/tech-debt/chico-features.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/en/tech-debt.md
> +![John is happy because he delivered the project in time](../../images/tech-debt/chico-delivered.png)
```suggestion
![John is happy because he delivered the project in time]({static}/images/tech-debt/chico-delivered.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/en/tech-debt.md
> +![Cat's reviewing John's code](../../images/tech-debt/chico-team-review.png)
```suggestion
![Cat's reviewing John's code]({static}/images/tech-debt/chico-team-review.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/en/tech-debt.md
> +![John is sad because his project had some bugs](../../images/tech-debt/chico-bugs.png)
```suggestion
![John is sad because his project had some bugs]({static}/images/tech-debt/chico-bugs.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/en/tech-debt.md
> +![John is happy again, he knows that in the future he'll fix everything](../../images/tech-debt/chico-refactoring-en.png)
```suggestion
![John is happy again, he knows that in the future he'll fix everything]({static}/images/tech-debt/chico-refactoring-en.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/en/tech-debt.md
> +![The problems in John’s project](../../images/tech-debt/problems-on-chicos-code-en.png)
```suggestion
![The problems in John’s project]({static}/images/tech-debt/problems-on-chicos-code-en.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/en/tech-debt.md
> +![Picture from the Tower under construction](../../images/tech-debt/pisa-tower-construction.png)
```suggestion
![Picture from the Tower under construction]({static}/images/tech-debt/pisa-tower-construction.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/en/tech-debt.md
> +![Loosing Quality vs. Speed up deliveries](../../images/tech-debt/tech-debt-tradeoff-en.png)
```suggestion
![Loosing Quality vs. Speed up deliveries]({static}/images/tech-debt/tech-debt-tradeoff-en.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/en/tech-debt.md
> +![Martin Fowler’s Technical Debt Quadrant](../../images/tech-debt/tech-debt-quadrant-en.png)
```suggestion
![Martin Fowler’s Technical Debt Quadrant]({static}/images/tech-debt/tech-debt-quadrant-en.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/en/tech-debt.md
> +![John is sad because his bad decisions also affect the project](../../images/tech-debt/our-responsability-en.png)
```suggestion
![John is sad because his bad decisions also affect the project]({static}/images/tech-debt/our-responsability-en.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/en/tech-debt.md
> +![Comic strip from the process of creating a new tech debt ticket and adding it to a backlog full of forgotten tickets using dead plants as an analogy](../../images/tech-debt/tech-debt-backlog.png)
```suggestion
![Comic strip from the process of creating a new tech debt ticket and adding it to a backlog full of forgotten tickets using dead plants as an analogy]({static}/images/tech-debt/tech-debt-backlog.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/en/tech-debt.md
> +![I.M.P.A.C.T cyclic process](../../images/tech-debt/impact.png)
```suggestion
![I.M.P.A.C.T cyclic process]({static}/images/tech-debt/impact.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/en/tech-debt.md
> +![Pareto principle demostrated using Pizza slices](../../images/tech-debt/pareto-principle-en.png)
```suggestion
![Pareto principle demostrated using Pizza slices]({static}/images/tech-debt/pareto-principle-en.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/en/tech-debt.md
> +![Cat's in a Tech Debt review](../../images/tech-debt/tech-debt-review.png)
```suggestion
![Cat's in a Tech Debt review]({static}/images/tech-debt/tech-debt-review.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/en/tech-debt.md
> +![Chart comparison of the two approaches of software coding](../../images/tech-debt/next-feature-cost.png)
```suggestion
![Chart comparison of the two approaches of software coding]({static}/images/tech-debt/next-feature-cost.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/en/tech-debt.md
> +![The cost of low-quality software: 2.84 trilion dolares](../../images/tech-debt/bad-quality-software-costs-en.png)
```suggestion
![The cost of low-quality software: 2.84 trilion dolares]({static}/images/tech-debt/bad-quality-software-costs-en.png)
```

2020-10-06 17:52 UTC, fernandolins commented on content/articles/en/tech-debt.md
> +![Famous Pisa Tower picture with a lot of tourist taking photos when trying to push it back](../../images/tech-debt/pisa-tower-is-sustainable-en.png)
```suggestion
![Famous Pisa Tower picture with a lot of tourist taking photos when trying to push it back]({static}/images/tech-debt/pisa-tower-is-sustainable-en.png)
```

2020-10-07 14:22 UTC, luanfonceca commented
@fernandolins I just did all the changes you asked for.
Here's the commit: https://github.com/labcodes/blog/pull/99/commits/52bad751b9d2b8a1914626db07d50c2cf4a987ba

2020-10-09 15:07 UTC, fernandolins requested changes

2020-10-09 15:07 UTC, fernandolins commented on content/articles/pt/tech-debt.md
> +url: pt/articles/tech-debt.html
```suggestion
slug: tech-debt
```

2020-10-09 15:07 UTC, fernandolins commented on content/articles/en/tech-debt.md
> +url: articles/tech-debt.html
```suggestion
slug: tech-debt
```

2020-10-09 15:13 UTC, fernandolins approved these changes
LGTM

2020-10-09 15:16 UTC, merged